name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v2 to v4
      with:
        fetch-depth: 0  # Gets full git history for Gradle

    - name: Set up JDK
      uses: actions/setup-java@v3  # Updated from v1 to v3
      with:
        java-version: '8'  # Changed from 1.8 to '8' (string format)
        distribution: 'temurin'  # Added recommended distribution

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace --info  # Added debug flags

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4  # More reliable than mr-smithers
      with:
        context: .
        push: true
        tags: nanajanashia/demo-app:latest
