# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    - name: Verify Gradle wrapper execution
      run: ls -la gradlew  # Confirms `gradlew` exists and is executable

    - name: Convert Gradle wrapper to UNIX format (if needed)
      run: dos2unix gradlew || true  # Ensures correct execution format

    - name: Build with Gradle
      run: ./gradlew build || bash gradlew build  # Adds fallback execution method

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
