# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permissions to Gradle wrapper
      run: chmod +x gradlew

    - name: Verify Gradle wrapper execution
      run: ls -la gradlew  # Confirms `gradlew` exists and is executable

    - name: Convert Gradle wrapper to UNIX format (if needed)
      run: dos2unix gradlew || true  # Ensures correct execution format

    - name: Build with Gradle
      run: ./gradlew build || bash gradlew build  # Adds fallback execution method

    - name: Verify build output (Check if JAR file exists)
      run: ls -la build/libs/  # Ensures JAR file is present before Docker build
